### ISSUE TITLE
Wrong image paths

### ISSUE THREAD

**Issue by allipatev** [exasol/Public-Knowledgebase#15]
Please consider fixing image paths pointing to a fork:
https://github.com/exasol/Public-Knowledgebase/search?q=bailbot

**Comment by nconforti93** [comment]
@bailbot can you look at the files listed in the link above and change the images to the pictures to be relative paths? For an example, look at https://github.com/exasol/Public-Knowledgebase/blob/main/Support-and-Services/training-badge-associate.md
